port: /dev/dashgo
baud: 115200
timeout: 0.1
rate: 50
sensorstate_rate: 10

useImu: False
use_base_controller: True
base_controller_rate: 10

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_footprint

# === Robot drivetrain parameters
wheel_diameter: 0.162
wheel_track: 0.330
encoder_resolution: 730
gear_reduction: 0.975
motors_reversed: False

# === PID parameters
Kp: 50
Kd: 20
Ki: 0
Ko: 50
accel_limit: 1.0
